// <auto-generated />
using System;
using Address_Book.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Address_Book.Migrations
{
    [DbContext(typeof(AddressBookDbContext))]
    [Migration("20250803114805_UpdateSeedDataWithDiverseContacts")]
    partial class UpdateSeedDataWithDiverseContacts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("Address_Book.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("Province")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St",
                            City = "Cape Town",
                            CreatedAt = new DateTime(2024, 8, 2, 17, 48, 0, 0, DateTimeKind.Utc),
                            Email = "john.doe@gmail.com",
                            FullName = "John Doe",
                            PhoneNumber = "+27-21-123-4567",
                            Province = "Western Cape",
                            UpdatedAt = new DateTime(2024, 8, 2, 17, 48, 0, 0, DateTimeKind.Utc),
                            ZipCode = "8001"
                        },
                        new
                        {
                            Id = 2,
                            Address = "789 High Street",
                            City = "Pretoria",
                            CreatedAt = new DateTime(2024, 8, 2, 17, 48, 0, 0, DateTimeKind.Utc),
                            Email = "mpho.mokwena@outlook.com",
                            FullName = "Mpho Mokwena",
                            PhoneNumber = "+27-12-234-5678",
                            Province = "Gauteng",
                            UpdatedAt = new DateTime(2024, 8, 2, 17, 48, 0, 0, DateTimeKind.Utc),
                            ZipCode = "0001"
                        },
                        new
                        {
                            Id = 3,
                            Address = "456 Oak Avenue",
                            City = "Johannesburg",
                            CreatedAt = new DateTime(2024, 8, 2, 17, 48, 0, 0, DateTimeKind.Utc),
                            Email = "jane.smith@yahoo.com",
                            FullName = "Jane Smith",
                            PhoneNumber = "+27-11-234-5678",
                            Province = "Gauteng",
                            UpdatedAt = new DateTime(2024, 8, 2, 17, 48, 0, 0, DateTimeKind.Utc),
                            ZipCode = "2001"
                        },
                        new
                        {
                            Id = 4,
                            Address = "321 Pine Street",
                            City = "Pretoria",
                            CreatedAt = new DateTime(2024, 8, 2, 17, 48, 0, 0, DateTimeKind.Utc),
                            Email = "thabo.nkosi@hotmail.com",
                            FullName = "Thabo Nkosi",
                            PhoneNumber = "+27-12-345-6789",
                            Province = "Gauteng",
                            UpdatedAt = new DateTime(2024, 8, 2, 17, 48, 0, 0, DateTimeKind.Utc),
                            ZipCode = "0002"
                        },
                        new
                        {
                            Id = 5,
                            Address = "789 Pine Road",
                            City = "Durban",
                            CreatedAt = new DateTime(2024, 8, 2, 17, 48, 0, 0, DateTimeKind.Utc),
                            Email = "michael.johnson@icloud.com",
                            FullName = "Michael Johnson",
                            PhoneNumber = "+27-31-345-6789",
                            Province = "KwaZulu-Natal",
                            UpdatedAt = new DateTime(2024, 8, 2, 17, 48, 0, 0, DateTimeKind.Utc),
                            ZipCode = "4001"
                        },
                        new
                        {
                            Id = 6,
                            Address = "123 Willow Street",
                            City = "Durban",
                            CreatedAt = new DateTime(2024, 8, 2, 17, 48, 0, 0, DateTimeKind.Utc),
                            Email = "lindiwe.dlamini@live.com",
                            FullName = "Lindiwe Dlamini",
                            PhoneNumber = "+27-31-456-7890",
                            Province = "KwaZulu-Natal",
                            UpdatedAt = new DateTime(2024, 8, 2, 17, 48, 0, 0, DateTimeKind.Utc),
                            ZipCode = "4001"
                        },
                        new
                        {
                            Id = 7,
                            Address = "321 Elm Street",
                            City = "Bloemfontein",
                            CreatedAt = new DateTime(2024, 8, 2, 17, 48, 0, 0, DateTimeKind.Utc),
                            Email = "sarah.williams@protonmail.com",
                            FullName = "Sarah Williams",
                            PhoneNumber = "+27-51-456-7890",
                            Province = "Free State",
                            UpdatedAt = new DateTime(2024, 8, 2, 17, 48, 0, 0, DateTimeKind.Utc),
                            ZipCode = "9301"
                        },
                        new
                        {
                            Id = 8,
                            Address = "654 Maple Lane",
                            City = "Port Elizabeth",
                            CreatedAt = new DateTime(2024, 8, 2, 17, 48, 0, 0, DateTimeKind.Utc),
                            Email = "david.brown@zoho.com",
                            FullName = "David Brown",
                            PhoneNumber = "+27-41-567-8901",
                            Province = "Eastern Cape",
                            UpdatedAt = new DateTime(2024, 8, 2, 17, 48, 0, 0, DateTimeKind.Utc),
                            ZipCode = "6001"
                        },
                        new
                        {
                            Id = 9,
                            Address = "987 Cedar Road",
                            City = "Bloemfontein",
                            CreatedAt = new DateTime(2024, 8, 2, 17, 48, 0, 0, DateTimeKind.Utc),
                            Email = "sipho.khumalo@aol.com",
                            FullName = "Sipho Khumalo",
                            PhoneNumber = "+27-51-567-8901",
                            Province = "Free State",
                            UpdatedAt = new DateTime(2024, 8, 2, 17, 48, 0, 0, DateTimeKind.Utc),
                            ZipCode = "9301"
                        },
                        new
                        {
                            Id = 10,
                            Address = "456 Birch Street",
                            City = "Lephalale",
                            CreatedAt = new DateTime(2024, 8, 2, 17, 48, 0, 0, DateTimeKind.Utc),
                            Email = "deltaslep@gmail.com",
                            FullName = "Deltas Lephalala",
                            PhoneNumber = "+27-15-678-9012",
                            Province = "Limpopo",
                            UpdatedAt = new DateTime(2024, 8, 2, 17, 48, 0, 0, DateTimeKind.Utc),
                            ZipCode = "0555"
                        },
                        new
                        {
                            Id = 11,
                            Address = "234 Sunset Boulevard",
                            City = "East London",
                            CreatedAt = new DateTime(2024, 8, 2, 17, 48, 0, 0, DateTimeKind.Utc),
                            Email = "nomsa.mbeki@outlook.com",
                            FullName = "Nomsa Mbeki",
                            PhoneNumber = "+27-43-789-0123",
                            Province = "Eastern Cape",
                            UpdatedAt = new DateTime(2024, 8, 2, 17, 48, 0, 0, DateTimeKind.Utc),
                            ZipCode = "5201"
                        },
                        new
                        {
                            Id = 12,
                            Address = "567 Mountain View Drive",
                            City = "Worcester",
                            CreatedAt = new DateTime(2024, 8, 2, 17, 48, 0, 0, DateTimeKind.Utc),
                            Email = "pieter.vandermerwe@yahoo.com",
                            FullName = "Pieter van der Merwe",
                            PhoneNumber = "+27-23-890-1234",
                            Province = "Western Cape",
                            UpdatedAt = new DateTime(2024, 8, 2, 17, 48, 0, 0, DateTimeKind.Utc),
                            ZipCode = "6850"
                        },
                        new
                        {
                            Id = 13,
                            Address = "890 Valley Road",
                            City = "Pietermaritzburg",
                            CreatedAt = new DateTime(2024, 8, 2, 17, 48, 0, 0, DateTimeKind.Utc),
                            Email = "z.mthembu@hotmail.com",
                            FullName = "Zanele Mthembu",
                            PhoneNumber = "+27-33-901-2345",
                            Province = "KwaZulu-Natal",
                            UpdatedAt = new DateTime(2024, 8, 2, 17, 48, 0, 0, DateTimeKind.Utc),
                            ZipCode = "3201"
                        },
                        new
                        {
                            Id = 14,
                            Address = "123 Industrial Street",
                            City = "Klerksdorp",
                            CreatedAt = new DateTime(2024, 8, 2, 17, 48, 0, 0, DateTimeKind.Utc),
                            Email = "johan.pretorius@icloud.com",
                            FullName = "Johan Pretorius",
                            PhoneNumber = "+27-18-012-3456",
                            Province = "North West",
                            UpdatedAt = new DateTime(2024, 8, 2, 17, 48, 0, 0, DateTimeKind.Utc),
                            ZipCode = "2571"
                        },
                        new
                        {
                            Id = 15,
                            Address = "456 Heritage Lane",
                            City = "Rustenburg",
                            CreatedAt = new DateTime(2024, 8, 2, 17, 48, 0, 0, DateTimeKind.Utc),
                            Email = "tebogo.modise@live.com",
                            FullName = "Tebogo Modise",
                            PhoneNumber = "+27-14-123-4567",
                            Province = "North West",
                            UpdatedAt = new DateTime(2024, 8, 2, 17, 48, 0, 0, DateTimeKind.Utc),
                            ZipCode = "0300"
                        },
                        new
                        {
                            Id = 16,
                            Address = "789 Coastal Drive",
                            City = "George",
                            CreatedAt = new DateTime(2024, 8, 2, 17, 48, 0, 0, DateTimeKind.Utc),
                            Email = "michelle.roberts@protonmail.com",
                            FullName = "Michelle Roberts",
                            PhoneNumber = "+27-44-234-5678",
                            Province = "Western Cape",
                            UpdatedAt = new DateTime(2024, 8, 2, 17, 48, 0, 0, DateTimeKind.Utc),
                            ZipCode = "6529"
                        },
                        new
                        {
                            Id = 17,
                            Address = "321 Mining Avenue",
                            City = "Secunda",
                            CreatedAt = new DateTime(2024, 8, 2, 17, 48, 0, 0, DateTimeKind.Utc),
                            Email = "bongani.sibiya@zoho.com",
                            FullName = "Bongani Sibiya",
                            PhoneNumber = "+27-17-345-6789",
                            Province = "Mpumalanga",
                            UpdatedAt = new DateTime(2024, 8, 2, 17, 48, 0, 0, DateTimeKind.Utc),
                            ZipCode = "2302"
                        },
                        new
                        {
                            Id = 18,
                            Address = "654 Commerce Street",
                            City = "Sandton",
                            CreatedAt = new DateTime(2024, 8, 2, 17, 48, 0, 0, DateTimeKind.Utc),
                            Email = "anita.patel@aol.com",
                            FullName = "Anita Patel",
                            PhoneNumber = "+27-11-456-7890",
                            Province = "Gauteng",
                            UpdatedAt = new DateTime(2024, 8, 2, 17, 48, 0, 0, DateTimeKind.Utc),
                            ZipCode = "2196"
                        },
                        new
                        {
                            Id = 19,
                            Address = "987 Wine Route",
                            City = "Stellenbosch",
                            CreatedAt = new DateTime(2024, 8, 2, 17, 48, 0, 0, DateTimeKind.Utc),
                            Email = "francois.dutoit@mail.com",
                            FullName = "Francois du Toit",
                            PhoneNumber = "+27-21-567-8901",
                            Province = "Western Cape",
                            UpdatedAt = new DateTime(2024, 8, 2, 17, 48, 0, 0, DateTimeKind.Utc),
                            ZipCode = "7600"
                        },
                        new
                        {
                            Id = 20,
                            Address = "147 Golden Gate Road",
                            City = "Bethlehem",
                            CreatedAt = new DateTime(2024, 8, 2, 17, 48, 0, 0, DateTimeKind.Utc),
                            Email = "lerato.maboe@yandex.com",
                            FullName = "Lerato Maboe",
                            PhoneNumber = "+27-58-678-9012",
                            Province = "Free State",
                            UpdatedAt = new DateTime(2024, 8, 2, 17, 48, 0, 0, DateTimeKind.Utc),
                            ZipCode = "9700"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
